import { LOCAL_TEXT } from '@/shared/consts/local-text';

export const STEPS_CARDS_ITEMS = [
  {
    description: LOCAL_TEXT.INVESTOR_PAGE.TOKEN_LAUNCH.CARDS.ONE.VALUE,
    highlight: [
      LOCAL_TEXT.INVESTOR_PAGE.TOKEN_LAUNCH.CARDS.ONE.HIGHLIGHT.ONE,
      LOCAL_TEXT.INVESTOR_PAGE.TOKEN_LAUNCH.CARDS.ONE.HIGHLIGHT.TWO,
    ],
  },
  {
    description: LOCAL_TEXT.INVESTOR_PAGE.TOKEN_LAUNCH.CARDS.TWO.VALUE,
    highlight: LOCAL_TEXT.INVESTOR_PAGE.TOKEN_LAUNCH.CARDS.TWO.HIGHLIGHT,
  },
  {
    description: LOCAL_TEXT.INVESTOR_PAGE.TOKEN_LAUNCH.CARDS.THREE.VALUE,
    highlight: LOCAL_TEXT.INVESTOR_PAGE.TOKEN_LAUNCH.CARDS.THREE.HIGHLIGHT,
  },
  {
    description: LOCAL_TEXT.INVESTOR_PAGE.TOKEN_LAUNCH.CARDS.FOUR.VALUE,
    highlight: [
      LOCAL_TEXT.INVESTOR_PAGE.TOKEN_LAUNCH.CARDS.FOUR.HIGHLIGHT.ONE,
      LOCAL_TEXT.INVESTOR_PAGE.TOKEN_LAUNCH.CARDS.FOUR.HIGHLIGHT.TWO,
    ],
  },
  {
    description: LOCAL_TEXT.INVESTOR_PAGE.TOKEN_LAUNCH.CARDS.FIVE.VALUE,
    highlight: [
      LOCAL_TEXT.INVESTOR_PAGE.TOKEN_LAUNCH.CARDS.FIVE.HIGHLIGHT.ONE,
      LOCAL_TEXT.INVESTOR_PAGE.TOKEN_LAUNCH.CARDS.FIVE.HIGHLIGHT.TWO,
    ],
  },
];
