import { DEFAULT } from '@/shared/consts';
import { LOCAL_TEXT } from '@/shared/consts/local-text';

export const STEPS_CARDS_ITEMS: {
  title: string;
  titleHighlight: string;
  descriptions: string;
  highlight: string;
  value?: number;
}[] = [
  {
    title: LOCAL_TEXT.INVESTOR_PAGE.TOKENOMIC.CARDS.ONE.TITLE,
    titleHighlight:
      LOCAL_TEXT.INVESTOR_PAGE.TOKENOMIC.CARDS.ONE.TITLE_HIGHLIGHT,
    descriptions: LOCAL_TEXT.INVESTOR_PAGE.TOKENOMIC.CARDS.ONE.DESCRIPTIONS,
    highlight: LOCAL_TEXT.INVESTOR_PAGE.TOKENOMIC.CARDS.ONE.HIGHLIGHT,
  },
  {
    title: LOCAL_TEXT.INVESTOR_PAGE.TOKENOMIC.CARDS.TWO.TITLE,
    titleHighlight:
      LOCAL_TEXT.INVESTOR_PAGE.TOKENOMIC.CARDS.TWO.TITLE_HIGHLIGHT,
    descriptions: LOCAL_TEXT.INVESTOR_PAGE.TOKENOMIC.CARDS.TWO.DESCRIPTIONS,
    highlight: LOCAL_TEXT.INVESTOR_PAGE.TOKENOMIC.CARDS.TWO.HIGHLIGHT,
  },
  {
    title: LOCAL_TEXT.INVESTOR_PAGE.TOKENOMIC.CARDS.THREE.TITLE,
    titleHighlight:
      LOCAL_TEXT.INVESTOR_PAGE.TOKENOMIC.CARDS.THREE.TITLE_HIGHLIGHT,
    descriptions: LOCAL_TEXT.INVESTOR_PAGE.TOKENOMIC.CARDS.THREE.DESCRIPTIONS,
    highlight: LOCAL_TEXT.INVESTOR_PAGE.TOKENOMIC.CARDS.THREE.HIGHLIGHT,
  },
  {
    title: LOCAL_TEXT.INVESTOR_PAGE.TOKENOMIC.CARDS.FOUR.TITLE,
    titleHighlight:
      LOCAL_TEXT.INVESTOR_PAGE.TOKENOMIC.CARDS.FOUR.TITLE_HIGHLIGHT,
    descriptions: LOCAL_TEXT.INVESTOR_PAGE.TOKENOMIC.CARDS.FOUR.DESCRIPTIONS,
    highlight: LOCAL_TEXT.INVESTOR_PAGE.TOKENOMIC.CARDS.FOUR.HIGHLIGHT,
    value: DEFAULT.MIN_BUY_TOKEN,
  },
];
