export const AWARDS_TASKS = {
  BYBIT: 'bybit',
  CHECKIN: 'checkin',
  FRIEND_INVITE: 'friend-invite',
  WALLET: 'wallet',
  WELCOME_BONUS: 'welcome-bonus',
  SHARE_IN_STORIES: 'shere-in-stories',
  ACCOUNT_BIO: 'account-bio',
  WEB_URL: 'web-url',
  OPEN_X: 'open-x',
  OPEN_TG: 'open-tg',
  OPEN_YOUTUBE: 'open-youtube',
  OPEN_TIKTOK: 'open-tiktok',
  OPEN_REDDIT: 'open-reddit',
  OPEN_DISCORD: 'open-discord',
  OPEN_WHITEPAPER: 'open-whitepaper',
  OPEN_PITCHDEK: 'open-pitchdek',
  WATCH_START_VIDEO: 'watch-start-video',
  WATCH_INSTRUCTION: 'whached_instruction',

  SAM_RU: 'sam-ru',
  SAM_ENG: 'sam-eng',
  INST_RU: 'inst-ru',
  INST_ENG: 'inst-eng',

  OPEN_TG_ENG: 'open-tg-eng',
  OPEN_TG_CHAT: 'open-tg-chat',
  OPEN_TG_CHAT_ENG: 'open-tg-chat-eng',
};
