export const QUERY_KEYS = {
  ACCOUNT: 'account',
  ALL_VIDEO: 'allVideo',
  AWARDS: 'awards',
  BALANCES: 'balances',
  LIDEER_VIDEO: 'liderVideo',
  ME: 'me',
  REF: 'ref',
  REFERALS: 'referals',
  VIEWS: 'views',
  USER: 'user',
  ALL_USERS: 'all_users',
  TRANSACTION_SUM: 'transaction_sum',
  PRESALE_TOKEN_SUM: 'presale_token_sum',
  LOGIN: 'login',
  JETTON_WALLET_ADDRESS: 'jettonWalletAddress',

  STAKING_BY_ID: 'stakingById',
  STAKING_REFERRAL: 'stakingreferral',
  STAKING_USER: 'stakingUser',
};
